# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 38dc438ad969a05905053174eab94c28f89ca194fafbda0a0c34d7188a12d50a51be4a4021438851a2580efb6d00335787c15d73baedc150fcee38fed75649e3

test:
  secret_key_base: 5be85330ea2f68feb7035859f05196cff635ac2b5eb74105595134e81584423de714b1f79dc4dcf296a7754df8d6891dd28526db7624c8390cd9d81444494073

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
